# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c51583663733aabe554373a2bee43739c6c63041ea9e82f78b5d43348bb108862ba8d97569e4e0b2a5b3d033e815d25d1a57871d131d1fb72b0998908c5e2d

test:
  secret_key_base: fc20c6346776cc3d19cf415d950791eb9d70b62a7d471a9774a734e5957ad3fa1f3903ce7b2e3c5b698f55cc6d80ea23a16aa3d89c814964a34dd82513200150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
